### ISSUE TITLE
about the skin

### ISSUE THREAD

**Issue by bcliutong** [myflashlab/surfaceVideoPlayer-ANE#1]
hi and thanks for sharing, and I have a question about the player's skin[code:C.startOnStage(this, "`", 1);], if i want to create a player with normal skin ,what should be set to the third parameter ? I've tried several values,but the skin is always empty...

**Comment by imalitavakoli** [comment]
@bcliutong this ANE is actually an abstract video player... It doesn't have any skins my friend :)
but as it's so powerful you can aslo build your own skin and control the video by using the Extension's different methods like `_ex.play();` and other methods, so that for example when you click your own play button, the video will be played. Please read the Extension's documentation carefully, it clearly explains you how to use it.

**P.S.** If you don't like to use this Surface Video Player which is an 'Abstract' player, you may like to also take a look at http://myappsnippet.com/video-player-native-extension/
This one, simply opens the Device's native video player and plays your video.

**Comment by myflashlab** [comment]
خوندم اينو... آخه ما كه اِسكين نداريم! خودش بايد بسازه!
