### ISSUE TITLE
Video rotation possibility

### ISSUE THREAD

**Issue by DPedneault** [myflashlab/surfaceVideoPlayer-ANE#8]
Hi!

I was simply wondering if there was a possibility to add a video rotation capability to this ANE, so that the video could be angled.  Is there any technical limitation in Android/iOS preventing this feature from being added in the future?

Thank you!

**Comment by myflashlab** [comment]
With V3.2.0 released today, we fixed a problem when your app orientation was changing and the video dimensions were missed! That is fixed now. but supporting the actual video object to be rotated, I'm not sure that feature is popular enough. since your last post, no one else requested such a feature. so I have to close this ticket for now. If you really need it though, you can [contact us here](http://www.myflashlabs.com/contact/) as a custom job order. Thanks.
